server:
  port: 8080
  address: 0.0.0.0

spring:
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true

  kafka:
    bootstrap-servers: ${SPRING_KAFKA_BOOTSTRAP_SERVERS:kafka:9092}
    admin:
      auto-create: true
    consumer:
      group-id: history-consumer-group
      auto-offset-reset: earliest
      enable-auto-commit: false
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer

  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog-master.xml